<script setup>
import { ArrowRight, Play, BookOpen, Gamepad2, PencilLine, ChartNoAxesColumnIncreasing, Sparkles, ShieldCheck, Download } from 'lucide-vue-next'
import { programs, games, resources, naira } from '../../data/content'
import hero from '../../assets/images/bg.png'
import culture from '../../assets/images/background.png'
import books from '../../assets/images/books.png'
import WaveDivider from '../../components/WaveDivider.vue'
</script>
<template><div class="home-page"><section class="hero has-wave"><div class="shell hero-grid"><div class="hero-copy"><span class="eyebrow"><Sparkles :size="15"/> Learning made joyful</span><h1>Learn.<br><em>Grow.</em><br><strong>Shine!</strong></h1><p>One guided place for little learners to discover new skills, practise with play, and grow in confidence every day.</p><div class="hero-actions"><RouterLink class="button" to="/register">Start learning free <ArrowRight :size="18"/></RouterLink><RouterLink class="watch-link" to="/programs"><span><Play :size="18" fill="currentColor"/></span>See how Edyn works</RouterLink></div><div class="trust-row"><div class="mini-avatars"><b>T</b><b>A</b><b>K</b></div><p><strong>Made with educators</strong><br>Trusted by growing families</p></div></div><div class="hero-art"><img :src="hero" alt="Two joyful Edyn learners ready for school"><div class="floating-note note-one">★ 6 day streak</div><div class="floating-note note-two">A+ Great work!</div></div></div><WaveDivider position="bottom" color="#fffdf8" :height="88" flip /></section>
<section class="promise-strip shell"><article><BookOpen/><div><b>Guided lessons</b><span>Clear learning paths</span></div></article><article><Gamepad2/><div><b>Play to practise</b><span>Reusable learning games</span></div></article><article><PencilLine/><div><b>Build real skills</b><span>Digital and printable practice</span></div></article><article><ChartNoAxesColumnIncreasing/><div><b>See their progress</b><span>Simple insights for parents</span></div></article></section>
<section class="section shell"><div class="section-heading"><span class="eyebrow soft">A bright beginning</span><h2>Everything connects to help<br><em>your child move forward.</em></h2><p>A gentle rhythm of learning, play, practice and encouragement—built around each child’s progress.</p></div><div class="journey"><article><span>01</span><BookOpen/><h3>Learn</h3><p>Meet one clear idea in a short, engaging lesson.</p></article><i>→</i><article><span>02</span><Gamepad2/><h3>Play</h3><p>Strengthen the same skill through a joyful game.</p></article><i>→</i><article><span>03</span><PencilLine/><h3>Practise</h3><p>Try it independently, online or on paper.</p></article><i>→</i><article><span>04</span><ChartNoAxesColumnIncreasing/><h3>Grow</h3><p>Edyn tracks progress and chooses what comes next.</p></article></div></section>
<section class="section tinted wave-section"><WaveDivider position="top" color="#fffdf8" :height="72"/><div class="shell"><div class="split-heading"><div><span class="eyebrow soft">Learning programs</span><h2>Big learning, built from<br><em>small happy steps.</em></h2></div><RouterLink class="arrow-link" to="/programs">Explore all programs <ArrowRight :size="18"/></RouterLink></div><div class="program-grid"><RouterLink v-for="program in programs.slice(0,4)" :key="program.slug" :to="`/courses/${program.slug}`" class="program-card" :class="program.color"><div class="program-image"><img :src="program.image" :alt="program.title"><span>{{program.age}}</span></div><small>{{program.subject}}</small><h3>{{program.title}}</h3><p>{{program.description}}</p><b class="card-link">Explore program <ArrowRight :size="17"/></b></RouterLink></div></div><WaveDivider position="bottom" color="#fffdf8" :height="72" flip/></section>
<section class="section shell game-preview"><div class="game-copy"><span class="eyebrow"><Gamepad2 :size="15"/> Edyn Game Hub</span><h2>Practice that feels<br><em>like playtime.</em></h2><p>Quick, positive games turn new ideas into skills children remember. Each game feeds progress back into their learning journey.</p><ul><li>Large, child-friendly controls</li><li>Gentle feedback and audio prompts</li><li>Skills matched to each lesson</li></ul><RouterLink class="button" to="/games">Visit the game hub <ArrowRight :size="18"/></RouterLink></div><div class="game-stack"><article v-for="game in games.slice(0,3)" :key="game.slug" :class="game.color"><span>{{game.icon}}</span><div><small>{{game.category}}</small><h3>{{game.title}}</h3><p>{{game.instruction}}</p></div><Play fill="currentColor"/></article></div></section>
<section class="culture shell"><img :src="culture" alt="Edyn learners discovering the world"><div><span class="eyebrow light">Rooted here. Ready for the world.</span><h2>Proudly Nigerian.<br><em>Globally inspired.</em></h2><p>Learning that feels familiar, celebrates every child and opens up a world of possibility.</p></div></section>
<section class="section shell"><div class="split-heading"><div><span class="eyebrow soft">Resource store</span><h2>Keep the learning going<br><em>beyond the screen.</em></h2></div><RouterLink class="arrow-link" to="/resources">Shop all resources <ArrowRight :size="18"/></RouterLink></div><div class="resource-row"><RouterLink v-for="item in resources.slice(0,4)" :key="item.slug" :to="`/resources/${item.slug}`" class="resource-card"><div class="resource-cover" :class="item.color"><small>EDYN</small><strong>{{item.letter}}</strong><span>{{item.type}}</span></div><div><small>{{item.age}} · {{item.type}}</small><h3>{{item.title}}</h3><p>{{naira(item.price)}}</p></div></RouterLink></div><div class="assurance-row"><span><ShieldCheck/> Educator-created</span><span><Download/> Instant downloads</span><span><Sparkles/> Made for young minds</span></div></section>
</div></template>
